version: "3.8"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3031:5173"
    volumes:
      - /app/node_modules
    environment:
      - VITE_APP_API_URL=${VITE_APP_API_URL:-}
