version: '3.9'

services:
   api:
      container_name: imdb_clone_api
      build:
         context: .
         target: debug
      ports:
         - 8020:8080
      volumes:
         - .:/usr/src/app
         - /usr/src/app/node_modules

      environment:
         - PORT=${PORT:-}
         - NODE_ENV=${NODE_ENV:-}
         - MONGO_URI=${MONGO_URI:-}
         - TOKEN_EXPIRATION=${TOKEN_EXPIRATION:-}
         - JWT_SECRET=${JWT_SECRET:-}
